db models added
temurchichua/AI_Hortens_IA pull request #10
Opened 2021-06-02 17:48 UTC by sun-dro

2021-06-02 18:18 UTC, temurchichua requested changes
მეორე იუზერს ადმინის როლი მოვხვსნათ და good to go

2021-06-02 18:18 UTC, temurchichua commented on project/commands/db_init.py
> +                        role=admin_role)
მოდი მეორეს არ მივცეთ ადმინის როლი, განსხვავებული ფუნქციონალის ტესტირებისთვის.

2021-06-02 21:23 UTC, Denissant commented on project/commands/db_init.py
> +                        role=admin_role)
Ticket-ების მოდელს სჭირდება `__init__`:

```python
    def __init__(self):
        self.date = datetime.datetime.now()
```

2021-06-03 06:35 UTC, sun-dro commented
გავასწორე

2021-06-03 06:36 UTC, merged